name: stpvelox
description: "StpVelox is the new environment running on the wombat - Fast and Sleek"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  yaml: ^3.1.2
  xterm: ^4.0.0
  collection: ^1.17.0
  circular_seek_bar: ^1.1.1
  fl_chart: ^1.0.0
  sleek_circular_slider:
    git:
      url: "git@github.com:htl-stp-ecer/sleek_circular_slider.git"
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.0.1
  riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1
  go_router: ^16.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  hooks_riverpod: ^3.0.1
  flutter_hooks: ^0.21.3+1
  logging: ^1.3.0
  raccoon_transport:
    path: packages/raccoon-transport/dart
  rxdart: ^0.28.0
  raccoon_ring_transport:
    path: packages/raccoon_ring_transport
  ffi: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  riverpod_generator: ^3.0.1
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.1
  mocktail: ^1.0.5


dependency_overrides:
  vector_math: 2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/